# -*- conf -*-

[main]
term=xterm-256color
pad=0x0
font=Rec Mono Casual:size=11
bold-text-in-bright=palette-based
initial-window-size-chars = 120x28

[scrollback]
lines=100000

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste

[colors]
#alpha=0.9
