# -*- conf -*-

[main]
term=xterm-256color
pad=12x0
font=RecMono Casual:size=10.0
bold-text-in-bright=palette-based
initial-window-size-chars = 120x28
include = ~/.config/foot/themes/perona.ini

[scrollback]
lines=100000

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
