[main]
term=xterm-256color
pad=12x0
font=RecMono Casual:size=11.0
bold-text-in-bright=palette-based
initial-window-size-chars = 120x28
include=~/.config/foot/themes/${THEME_NAME}.ini

#[colors]
#alpha=0.9

[scrollback]
lines=100000

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste

[bell]
command=pw-play /usr/share/sounds/freedesktop/stereo/bell.oga
command-focused=no
notify=no
visual=no
