music_directory			"~/m/mus"
playlist_directory	"~/.config/mpd/playlists"
db_file							"~/.config/mpd/database"
auto_update					"yes"
pid_file						"~/.config/mpd/pid"
state_file					"~/.local/state/mpd"

audio_output	{
	type		"pipewire"
	name		"PipeWire Sound Server"
}

decoder	{
	plugin	"wildmidi"
	enabled	"no"
}
