[env]
term = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 28 }
padding = { x = 12, y = 0}

[colors]
draw_bold_text_with_bright_colors = true

[general]
import = ["~/.config/alacritty/themes/perona.toml"]

[font]
normal = { family = "Cozette", style = "Regular" }
size = 10.0
