[env]
term = "xterm-256color"

[general]
import = [ "~/.config/alacritty/moonqueen.toml" ]

[font]
normal = { family = "Cozette" }
size = 11.0

[window]
dimensions = { columns = 120, lines = 28 }

[colors]
draw_bold_text_with_bright_colors = true
