set nocompatible
set hidden

" == editing =======================

filetype on
filetype plugin on
set background=dark
colorscheme luna
syntax on

set autoindent
set backspace	  =indent,eol,start
set breakindent
set expandtab
set linebreak
set re          =0
set softtabstop =4
set shiftwidth	=4
set shiftround
set showmatch
set wrap

" == display =======================

set colorcolumn =80,100
set display     =lastline
set number 
set modeline
set report      =0
set showcmd
set showmode
set ruler
set t_Co        =16
set novisualbell
set noerrorbells

" == plugins =======================

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'alvan/vim-closetag'
Plug 'jiangmiao/auto-pairs'
Plug 'mattn/emmet-vim'
Plug 'preservim/vim-markdown'
let g:polyglot_disabled = ['markdown']
Plug 'sheerun/vim-polyglot'
" Plug 'xavierd/clang_complete'
call plug#end()

" == navigation ====================

set scrolloff   =4
set ttyfast
set lazyredraw
set hlsearch
set incsearch
set ignorecase
set smartcase

" == changes =======================

set autoread

set backup
set writebackup
set noswapfile

set backupdir=~/.local/state/vim/backup//
set undodir=~/.local/state/vim/undo//
set undofile

set backupext=-vimbackup
set history=1000
set updatecount=100
set undolevels=1000

" == keybindings ==================

let mapleader = " "

" buffers
nnoremap <leader>bn :next<CR>
nnoremap <leader>bp :prev<CR>
nnoremap <leader>bd :bdelete<CR>

" windows
nnoremap <leader>vs :vsplit<CR>
" move between
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
" resize
nnoremap <A-h> 1<C-w>>
nnoremap <A-j> 1<C-w>-
nnoremap <A-k> 1<C-w>+
nnoremap <A-l> 1<C-w><
" close
nnoremap <leader>x :close<CR>

" indent in visual mode
vnoremap <Tab> >
vnoremap <S-Tab> <
