#!/usr/bin/env bash
set -euo pipefail

THEMES_DIR="$HOME/.config/themes"
OUT_DIR="$THEMES_DIR/generated"

mkdir -p "$OUT_DIR"

for file in "$THEMES_DIR"/*.json; do
  [ -f "$file" ] || continue
  name=$(basename "$file" .json)
  out="$OUT_DIR/$name.sh"

  {
    echo "# Autogenerated from $file"
    echo "export THEME_NAME=$name"
    jq -r 'to_entries | .[] | "export COLOR_\(.key|ascii_upcase)=\(.value)"' "$file"
  } > "$out"

  echo "Generated $out"
done
