# -*- rose pine tty colors -*-

if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0 #191724"
    echo -en "\x1b]P1 #eb6f92"
    echo -en "\x1b]P3 #f6c177"
    echo -en "\x1b]P4 #31748f"
    echo -en "\x1b]P5 #9ccfd8"
    echo -en "\x1b]P6 #c4a7e7"
    echo -en "\x1b]P7 #e0def4"
    echo -en "\x1b]P8 #47435d"
    echo -en "\x1b]P9 #ff98ba"
    echo -en "\x1b]PA #ffeb9e"
    echo -en "\x1b]PB #ffe5e3"
    echo -en "\x1b]PC #59546d"
    echo -en "\x1b]PD #c5f9ff"
    echo -en "\x1b]PE #eed0ff"
    echo -en "\x1b]PF #e0def4"
    clear
fi
