#!/bin/sh
if [ "$TERM" = "linux" ]; then
    echo -en "\x1b]P0191724"
    echo -en "\x1b]P1eb6f92"
    echo -en "\x1b]P231748f"
    echo -en "\x1b]P3f6c177"
    echo -en "\x1b]P49ccfd8"
    echo -en "\x1b]P5c4a7e7"
    echo -en "\x1b]P6ebbcba"
    echo -en "\x1b]P7e0def4"
    echo -en "\x1b]P847435d"
    echo -en "\x1b]P9ff98ba"
    echo -en "\x1b]PA5b9ab7"
    echo -en "\x1b]PBffeb9e"
    echo -en "\x1b]PCc5f9ff"
    echo -en "\x1b]PDeed0ff"
    echo -en "\x1b]PEffe5e3"
    echo -en "\x1b]PFe0def4"
    clear
fi
