[main]
term=xterm-256color
pad=12x0
font=RecMono Casual:size=12.0
#bold-text-in-bright=yes
initial-window-size-chars = 120x28

#[colors]
#alpha=0.9

[scrollback]
lines=100000

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste

[bell]
command=pw-play /usr/share/sounds/freedesktop/stereo/bell.oga
command-focused=no
notify=no
visual=no

# -*- luna -*-

[colors]
foreground=EAD9F2
background=271B2D
selection-background=B27DE8
selection-foreground=271B2D
urls=7DB2E8
flash=B27DE8

regular0=372640
regular1=F07575
regular2=D1F075
regular3=F0D175
regular4=7DB2E8
regular5=B27DE8
regular6=E87DB3
regular7=F8EBFF

bright0=483253
bright1=FA9E9E
bright2=E3FA9E
bright3=FAE39E
bright4=A3CCF5
bright5=CCA3F5
bright6=F5A3CC
bright7=EAD9F2
