set nocompatible
set hidden

" == paths =======================

if empty($XDG_DATA_HOME)
  let $XDG_DATA_HOME = $HOME . '/.local/share'
endif

if empty($XDG_STATE_HOME)
  let $XDG_STATE_HOME = $HOME . '/.local/state'
endif

let data_dir = $XDG_DATA_HOME . '/vim'

set runtimepath^=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim/after

" == plugins =======================

if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo ' . shellescape(data_dir . '/autoload/plug.vim') . ' --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin(data_dir . '/plugged')
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-surround'
    Plug 'sheerun/vim-polyglot'
    Plug 'ssh://softserve/ulti', { 'rtp': 'extras/vim', 'as': 'ulti' }
    Plug '~/p/lisp/kamakura', { 'rtp': 'extras/vim', 'as': 'kamakura' }
call plug#end()

" == editing =======================

filetype on
filetype plugin on

set background=light
set termguicolors
syntax enable

colorscheme kamakura

set autoindent
set backspace=indent,eol,start
set breakindent
set expandtab
set linebreak
set re=0
set softtabstop=4
set shiftwidth=4
set shiftround
set showmatch
set wrap
set nofoldenable

" == display =======================

set colorcolumn=80
set display=lastline
set number
set modeline
set report=0
set showcmd
set showmode
set ruler
set novisualbell
set noerrorbells

" == navigation ====================

set scrolloff=12
set ttyfast
set lazyredraw
set hlsearch
set incsearch
set ignorecase
set smartcase

" == changes =======================

set autoread

set backup
set writebackup
set noswapfile

set spellfile=$XDG_DATA_HOME/vim/spell/en.utf-8.add " shared with neovim 
set viminfofile=$XDG_STATE_HOME/vim/viminfo
set backupdir=$XDG_STATE_HOME/vim/backup//
set undodir=$XDG_STATE_HOME/vim/undo//
set undofile

set backupext=-vimbackup
set history=1000
set updatecount=100
set undolevels=1000

" == keybindings ==================

let mapleader = " "

" buffers
nnoremap bn :next<CR>
nnoremap bp :prev<CR>
nnoremap bd :bdelete<CR>

" windows
nnoremap <leader>vs :vsplit<CR>

" move between windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" resize windows
nnoremap <A-h> 1<C-w>>
nnoremap <A-j> 1<C-w>-
nnoremap <A-k> 1<C-w>+
nnoremap <A-l> 1<C-w><

" close
nnoremap <leader>x :close<CR>

" indent in visual mode
vnoremap <Tab> >
vnoremap <S-Tab> <

" date insertion
inoremap <C-d> <C-r>=strftime('%Y-%m-%dT%H:%M:%S%z')<CR>
